FROM wordpress:apache

RUN rm -rf ./wp-content/plugins/akismet

RUN apt update && apt install -y ca-certificates openssl && update-ca-certificates

COPY --from=marcelndeffo/tesselite:debian  /usr/bin/spin-service  /usr/bin/

COPY --from=marcelndeffo/tesselite:debian  /usr/bin/tessel  /usr/bin/

CMD AUTO_BACKUP=/var/www/html spin-service apache2-foreground


