FROM golang:1.20-alpine3.18 as pre-build

WORKDIR /build

COPY src/proxy/ .

#Build binary
RUN go build -o main

FROM alpine:3.18

EXPOSE 8080

WORKDIR /run

COPY *.html .

COPY static static

#security: server permissions
RUN addgroup -S server && adduser -S -D -h /run server server

RUN chown -R server:server /var/log

USER server

#Copy binary
COPY --from=pre-build --chown=server:server /build/main /run

ENV PATH=$PATH:/run

CMD main