FROM wordpress:apache

RUN rm -rf ./wp-content/plugins/akismet

COPY --from=marcelndeffo/tesselite:debian /home/tesselite/spin-service  /home/tesselite/spin-service

RUN install /home/tesselite/spin-service /usr/bin

CMD AUTO_BACKUP=/var/www/html spin-service apache2-foreground


