version: "3.5"

services:

  web:
    container_name: web
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.04"
          memory: "100MB"
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    hostname: ai.tesselite
    image: marcelndeffo/tesselite:web-0.0.0
    build:
      context: ..
      dockerfile: .build/dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: curl ai.tesselite:8000 || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s
